title: Todo supervivencia # your site title
author: todosupervivencia_es
email: todosupervivenciaes@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Esto es la meta description del index me imagino
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://todosp.github.io/tdps" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: essupervivencia # replace with your_twitter_username or comment to remove link from footer
github_username:  my_blogg # replace with your_github_username or comment to remove link from footer
instagram_username: es_supervivencia # replace with your_instagram_username or comment to remove link from footer
facebook_username: todosupervivencia
social:
  name: Your Name
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

disqus:
  shortname: https-todosp-github-io-tdps  # to enable comments replace with your_disqus_shortname
  comments: true

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

lang: es_ES
google_tag_manager: ""

